# Generated by Django 5.1.7 on 2026-05-13 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        ('devices', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intrusionalert',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intrusionalert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device'),
        ),
        migrations.AddField(
            model_name='intrusionalert',
            name='source_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_alerts', to='monitoring.networkactivity'),
        ),
        migrations.AddField(
            model_name='intrusionalert',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='intrusionalert',
            index=models.Index(fields=['status', 'severity'], name='alerts_intr_status_803485_idx'),
        ),
        migrations.AddIndex(
            model_name='intrusionalert',
            index=models.Index(fields=['alert_type'], name='alerts_intr_alert_t_83f259_idx'),
        ),
        migrations.AddIndex(
            model_name='intrusionalert',
            index=models.Index(fields=['detected_at'], name='alerts_intr_detecte_103ca1_idx'),
        ),
    ]
