"use client";

import { AlertTriangle, BellRing, ShieldAlert, Siren } from "lucide-react";
import { toast } from "sonner";

import { Badge, DataTable, EmptyState, PageHeader, Panel, StatCard } from "@/components/portal/PortalUI";
import {
  useGetAlertsQuery,
  useGetAlertSummaryQuery,
  useUpdateAlertMutation,
} from "@/lib/redux/slices/AlertSlice";
import { formatDateTime, formatNumber, statusTone } from "@/lib/portal/formatters";

export default function AdminAlertsPage() {
  const { data: summary } = useGetAlertSummaryQuery();
  const { data: alerts = [], isLoading } = useGetAlertsQuery();
  const [updateAlert, { isLoading: updating }] = useUpdateAlertMutation();

  const handleStatusChange = async (id: number, status: "investigating" | "resolved") => {
    try {
      await updateAlert({ id, data: { status } }).unwrap();
      toast.success(`Alert marked as ${status}.`);
    } catch (error: any) {
      toast.error(error?.data?.detail ?? "Unable to update alert.");
    }
  };

  return (
    <div className="space-y-6 bg-slate-50 px-4 py-6 md:px-6 lg:px-8">
      <PageHeader
        eyebrow="Alert Management"
        title="Triage suspicious events and decide what needs action first."
        description="This page supports the NetGuard alert workflow by organizing intrusions, suspicious access attempts, and abnormal activity into a queue the IT team can work through."
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard icon={BellRing} label="Open alerts" value={formatNumber(summary?.pending_alerts)} detail="Unresolved events still waiting for action." tone="amber" />
        <StatCard icon={ShieldAlert} label="Critical alerts" value={formatNumber(summary?.critical_alerts)} detail="Immediate review required from the IT team." tone="rose" />
        <StatCard icon={AlertTriangle} label="Behavior anomalies" value={formatNumber(alerts.filter((alert) => alert.alert_type === "abnormal_activity").length)} detail="Activity spikes or strange traffic patterns." tone="violet" />
        <StatCard icon={Siren} label="Unknown device alerts" value={formatNumber(summary?.unknown_device_alerts)} detail="Unrecognized endpoints seen by the monitoring engine." tone="sky" />
      </div>

      <Panel title="Alert queue" description="Actionable incidents generated by the backend detection engine.">
        {isLoading ? (
          <EmptyState title="Loading alerts" description="Fetching the current intrusion and anomaly queue." />
        ) : alerts.length ? (
          <DataTable
            columns={[
              { key: "type", label: "Type" },
              { key: "target", label: "Target" },
              { key: "time", label: "Detected" },
              { key: "severity", label: "Severity" },
              { key: "status", label: "Status" },
              { key: "action", label: "Action" },
            ]}
            rows={alerts.map((alert) => ({
              type: alert.alert_type.replaceAll("_", " "),
              target: (
                <div>
                  <p>{alert.user_email || alert.device_name || "Network source"}</p>
                  <p className="text-xs text-slate-500">{alert.message}</p>
                </div>
              ),
              time: formatDateTime(alert.detected_at),
              severity: <Badge tone={statusTone(alert.severity)}>{alert.severity}</Badge>,
              status: <Badge tone={statusTone(alert.status)}>{alert.status}</Badge>,
              action: (
                <div className="flex gap-2">
                  <button
                    type="button"
                    disabled={updating || alert.status === "investigating"}
                    onClick={() => handleStatusChange(alert.id, "investigating")}
                    className="rounded-full border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-700 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Investigate
                  </button>
                  <button
                    type="button"
                    disabled={updating || alert.status === "resolved"}
                    onClick={() => handleStatusChange(alert.id, "resolved")}
                    className="rounded-full bg-slate-900 px-3 py-1.5 text-xs font-medium text-white disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    Resolve
                  </button>
                </div>
              ),
            }))}
          />
        ) : (
          <EmptyState title="No alerts in queue" description="There are no current alerts to triage." />
        )}
      </Panel>
    </div>
  );
}
