import { AlertTriangle, BellRing, ShieldAlert, Siren } from "lucide-react";
import { Badge, DataTable, PageHeader, Panel, StatCard } from "@/components/portal/PortalUI";

export default function AdminAlertsPage() {
  return (
    <div className="space-y-6 bg-slate-50 px-4 py-6 md:px-6 lg:px-8">
      <PageHeader
        eyebrow="Alert Management"
        title="Triage suspicious events and decide what needs action first."
        description="This page supports the alert system requirement of NetGuard by organizing events that result from intrusion detection, suspicious access, or policy violations."
      />

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <StatCard icon={BellRing} label="Open alerts" value="19" detail="Current incident and advisory events." tone="amber" />
        <StatCard icon={ShieldAlert} label="Critical alerts" value="4" detail="Immediate review required from IT staff." tone="rose" />
        <StatCard icon={AlertTriangle} label="Behavior anomalies" value="7" detail="Unusual login or access behavior flagged." tone="violet" />
        <StatCard icon={Siren} label="Escalated today" value="3" detail="Alerts already promoted to active investigation." tone="sky" />
      </div>

      <Panel title="Alert queue" description="Actionable incidents generated by the detection engine.">
        <DataTable
          columns={[
            { key: "type", label: "Type" },
            { key: "target", label: "Target" },
            { key: "time", label: "Detected" },
            { key: "severity", label: "Severity" },
          ]}
          rows={[
            {
              type: "Invalid login attempts",
              target: "Admin account: network.ops",
              time: "Today, 09:16 AM",
              severity: <Badge tone="rose">Critical</Badge>,
            },
            {
              type: "Unknown device on restricted zone",
              target: "Engineering Lab VLAN",
              time: "Today, 08:43 AM",
              severity: <Badge tone="amber">High</Badge>,
            },
            {
              type: "Abnormal usage spike",
              target: "Student account: s10287",
              time: "Today, 08:02 AM",
              severity: <Badge tone="violet">Medium</Badge>,
            },
          ]}
        />
      </Panel>
    </div>
  );
}
