# Generated by Django 5.1.7 on 2026-05-13 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('iot', 'IoT'), ('other', 'Other')], default='other', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=100, unique=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('suspicious', 'Suspicious'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('is_registered', models.BooleanField(default=True)),
                ('registration_notes', models.TextField(blank=True)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['status'], name='devices_dev_status_bbf58f_idx'), models.Index(fields=['is_registered'], name='devices_dev_is_regi_f0d9e1_idx'), models.Index(fields=['owner'], name='devices_dev_owner_i_7ae9ba_idx')],
            },
        ),
    ]
