# Generated by Django 5.1.7 on 2026-05-13 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('login_attempt', 'Login Attempt'), ('logout', 'Logout'), ('session_start', 'Session Start'), ('session_end', 'Session End'), ('file_access', 'File Access'), ('restricted_access', 'Restricted Access'), ('download', 'Download'), ('upload', 'Upload'), ('network_scan', 'Network Scan'), ('configuration_change', 'Configuration Change')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('restricted', 'Restricted')], default='success', max_length=20)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('data_usage_mb', models.FloatField(default=0)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['activity_type', 'timestamp'], name='monitoring__activit_031dbe_idx'), models.Index(fields=['ip_address', 'timestamp'], name='monitoring__ip_addr_bbd487_idx'), models.Index(fields=['is_suspicious'], name='monitoring__is_susp_c8101e_idx'), models.Index(fields=['outcome'], name='monitoring__outcome_c17313_idx')],
            },
        ),
    ]
