# Generated by hand for network-edge control support.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0001_initial"),
        ("devices", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkEdgeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("radius_captive_portal", "RADIUS / Captive Portal"),
                            ("firewall_router", "Firewall / Router API"),
                            ("access_point_controller", "Access Point Controller"),
                        ],
                        max_length=50,
                    ),
                ),
                ("base_url", models.URLField(blank=True)),
                ("api_token", models.CharField(blank=True, max_length=255)),
                ("shared_secret", models.CharField(blank=True, max_length=255)),
                ("authorize_path", models.CharField(blank=True, default="/authorize", max_length=255)),
                ("revoke_path", models.CharField(blank=True, default="/revoke", max_length=255)),
                ("ban_path", models.CharField(blank=True, default="/ban", max_length=255)),
                ("unban_path", models.CharField(blank=True, default="/unban", max_length=255)),
                ("disconnect_path", models.CharField(blank=True, default="/disconnect", max_length=255)),
                ("health_path", models.CharField(blank=True, default="/health", max_length=255)),
                ("timeout_seconds", models.PositiveIntegerField(default=10)),
                ("enabled", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.CreateModel(
            name="NetworkEdgeActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("authorize", "Authorize Session"),
                            ("revoke", "Revoke Session"),
                            ("ban_mac", "Ban MAC"),
                            ("unban_mac", "Unban MAC"),
                            ("terminate_sessions", "Terminate Sessions"),
                            ("health_check", "Health Check"),
                        ],
                        max_length=50,
                    ),
                ),
                ("mac_address", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("status_code", models.CharField(blank=True, max_length=50)),
                ("message", models.TextField(blank=True)),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_edge_actions",
                        to="devices.device",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_network_edge_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to="security.networkedgeprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="network_edge_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["action"], name="sec_ne_act_idx"),
                    models.Index(fields=["success"], name="sec_ne_suc_idx"),
                    models.Index(fields=["created_at"], name="sec_ne_crt_idx"),
                ],
            },
        ),
    ]
