# Generated by Django 5.1.7 on 2026-06-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_networkedgeprofile_networkedgeactionlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='networkedgeactionlog',
            new_name='security_ne_action_cdac94_idx',
            old_name='sec_ne_act_idx',
        ),
        migrations.RenameIndex(
            model_name='networkedgeactionlog',
            new_name='security_ne_success_a5f73d_idx',
            old_name='sec_ne_suc_idx',
        ),
        migrations.RenameIndex(
            model_name='networkedgeactionlog',
            new_name='security_ne_created_6f1fa4_idx',
            old_name='sec_ne_crt_idx',
        ),
    ]
