# Generated by Django 5.1.7 on 2026-06-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_blockedentity_mac_address'),
        ('security', '0003_rename_sec_ne_act_idx_security_ne_action_cdac94_idx_and_more'),
    ]

    operations = [
    ]
