# Generated by Django 5.1.7 on 2026-05-13 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('USER_CREATE', 'User created'), ('USER_UPDATE', 'User updated'), ('USER_DELETE', 'User deleted'), ('USER_ACTIVATE', 'User activated'), ('USER_DEACTIVATE', 'User deactivated'), ('PASSWORD_RESET_REQUEST', 'Password reset requested'), ('PASSWORD_RESET_COMPLETE', 'Password reset completed'), ('PROFILE_UPDATE', 'Profile updated'), ('PERMISSION_CHANGE', 'User permissions changed'), ('EMAIL_SEND_FAILURE', 'Email delivery failed'), ('DEVICE_REGISTER', 'Device registered'), ('DEVICE_UPDATE', 'Device updated'), ('DEVICE_STATUS_CHANGE', 'Device status changed'), ('NETWORK_ACTIVITY_RECORDED', 'Network activity recorded'), ('ALERT_CREATE', 'Alert created'), ('ALERT_UPDATE', 'Alert updated'), ('SECURITY_BLOCK', 'Security block applied'), ('SECURITY_UNBLOCK', 'Security block removed'), ('REPORT_VIEW', 'Report viewed'), ('DASHBOARD_VIEW', 'Dashboard viewed'), ('USER_LIST_ACCESS', 'User list accessed'), ('USER_DETAIL_ACCESS', 'User detail accessed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('additional_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
