// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/About" | "/Admin" | "/Admin/Alerts" | "/Admin/Devices" | "/Admin/Network-Monitoring" | "/Admin/Profile-settings" | "/Admin/Reports" | "/Admin/Users" | "/Contact" | "/Features" | "/HeroSection" | "/auth" | "/auth/forgot" | "/guest" | "/guest/Profile-settings" | "/guest/Session-Info" | "/guest/Usage-Info" | "/student" | "/student/Profile-settings" | "/student/alerts" | "/student/my-activity" | "/student/my-devices"
type PageRoutes = never
type LayoutRoutes = "/" | "/Admin" | "/auth" | "/guest" | "/student"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/About": {}
  "/Admin": {}
  "/Admin/Alerts": {}
  "/Admin/Devices": {}
  "/Admin/Network-Monitoring": {}
  "/Admin/Profile-settings": {}
  "/Admin/Reports": {}
  "/Admin/Users": {}
  "/auth": {}
  "/auth/forgot": {}
  "/Contact": {}
  "/Features": {}
  "/guest": {}
  "/guest/Profile-settings": {}
  "/guest/Session-Info": {}
  "/guest/Usage-Info": {}
  "/HeroSection": {}
  "/student": {}
  "/student/alerts": {}
  "/student/my-activity": {}
  "/student/my-devices": {}
  "/student/Profile-settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/Admin": never
  "/auth": never
  "/guest": never
  "/student": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
